### PR TITLE
Add support for triggering a reset of the Console midrun

### PR DESCRIPTION
**Pull request by TheMas3212**
also fixed bug in loading runs that was causing transitions to be discarded on load

### CODE REVIEW

**Comment by Ownasaurus** [comment]
Could you explain the reset feature please? I don't fully understand it by reviewing the code. Thanks.

**Comment by Ownasaurus** [comment]
Hmm I get the general idea. I guess I just want to make sure it's been tested.

**Comment by TheMas3212** [comment]
Basicly it allows adding a transition that on the set frame triggers the console to reset, this was implemented for a run dwangoAC is currently trying to console verify that uses a reset part of the way through the run

**Comment by TheMas3212** [comment]
Its been used a couple of time already on dwangoAC's most recent stream

**Pull request merged**
